### ISSUE TITLE
how to use “scrollContainer” props?

### ISSUE THREAD

**Issue by ittat** [thcolin/react-responsive-virtual-grid#3]

**Comment by adamskoog** [comment]
This is used for when the container you want to be able to scroll within is not the full page. You need to pass the ref of the container element as the scrollContainer property. I'm using context, but you could easily pass it down as a prop as well if it's in a different component. Hopefully that helps.

If you want to see some code doing it you can check my implementation here: [Library Code](https://github.com/adamskoog/OnyxAudiobookPlayer/blob/master/src/components/Library/index.tsx)
This is my layout where I setup the ref: [Layout](https://github.com/adamskoog/OnyxAudiobookPlayer/blob/master/src/components/Layout/index.tsx)

**Comment by ittat** [comment]
I found that the scrollContainer property couldn't respond to changes, so I submitted a new PR https://github.com/thcolin/react-responsive-virtual-grid/pull/4
